import type { TemplateMeta } from "@/types/registry";

export const meta: TemplateMeta = {
  name: "launchui",
  title: "Launch UI",
  description:
    "A full landing page template with hero, logos, feature grid, stats, pricing, FAQ, CTA, and footer. Built with React, Shadcn/ui and Tailwind.",
  dependencies: [
    "lucide-react",
    "class-variance-authority",
    "@radix-ui/react-slot",
    "@radix-ui/react-accordion",
    "@radix-ui/react-dialog",
    "tw-animate-css",
  ],
  registryDependencies: [],
  cssVars: {
    light: {
      "--background": "oklch(97.65% 0.001 17.18)",
      "--foreground": "oklch(0.141 0.005 285.823)",
      "--primary": "oklch(66.5% 0.1804 47.04)",
      "--primary-foreground": "oklch(0.985 0 0)",
      "--muted": "oklch(0.967 0.001 286.375)",
      "--muted-foreground": "oklch(0.552 0.016 285.938)",
      "--border": "oklch(0.92 0.004 286.32)",
      "--card": "oklch(1 0 0)",
      "--card-foreground": "oklch(0.141 0.005 285.823)",
    },
    dark: {
      "--background": "oklch(0.141 0.005 285.823)",
      "--foreground": "oklch(0.985 0 0)",
      "--primary": "oklch(66.5% 0.1804 47.04)",
      "--primary-foreground": "oklch(0.985 0 0)",
      "--muted": "oklch(0.274 0.006 286.033)",
      "--muted-foreground": "oklch(0.705 0.015 286.067)",
      "--border": "oklch(0.274 0.006 286.033)",
      "--card": "oklch(0.141 0.005 285.823)",
      "--card-foreground": "oklch(0.985 0 0)",
    },
  },
  fileTargets: {
    "page.tsx": "app/page.tsx",
    "globals.css": "app/globals.css",
    "components/layout.tsx": "app/layout.tsx",
    "components/sections/nav.tsx": "components/launchui/sections/nav.tsx",
    "components/sections/hero.tsx": "components/launchui/sections/hero.tsx",
    "components/sections/logos.tsx": "components/launchui/sections/logos.tsx",
    "components/sections/items.tsx": "components/launchui/sections/items.tsx",
    "components/sections/stats.tsx": "components/launchui/sections/stats.tsx",
    "components/sections/pricing.tsx": "components/launchui/sections/pricing.tsx",
    "components/sections/faq.tsx": "components/launchui/sections/faq.tsx",
    "components/sections/cta.tsx": "components/launchui/sections/cta.tsx",
    "components/sections/footer.tsx": "components/launchui/sections/footer.tsx",
    "components/ui/section.tsx": "components/launchui/ui/section.tsx",
    "components/ui/button.tsx": "components/launchui/ui/button.tsx",
    "components/ui/badge.tsx": "components/launchui/ui/badge.tsx",
    "components/ui/glow.tsx": "components/launchui/ui/glow.tsx",
    "components/ui/mockup.tsx": "components/launchui/ui/mockup.tsx",
    "components/ui/navbar.tsx": "components/launchui/ui/navbar.tsx",
    "components/ui/item.tsx": "components/launchui/ui/item.tsx",
    "components/ui/footer.tsx": "components/launchui/ui/footer.tsx",
    "components/ui/accordion.tsx": "components/launchui/ui/accordion.tsx",
    "components/ui/sheet.tsx": "components/launchui/ui/sheet.tsx",
    "components/ui/link-button.tsx": "components/launchui/ui/link-button.tsx",
    "components/ui/pricing-column.tsx": "components/launchui/ui/pricing-column.tsx",
  },
};
